export const TEMPLATE_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "collections", label: "Collections" },
  { id: "reminder", label: "Reminder" },
  { id: "recovery", label: "Recovery" },
  { id: "lead-qualification", label: "Lead qualification" },
  { id: "appointments", label: "Appointments" },
];

export const SERVICE_TEMPLATES = [
  {
    id: "appointments",
    category: "appointments",
    name: "Appointment management",
    direction: "inbound",
    useCase: "Turn customer calls into instant bookings, reschedules, and confirmations with an AI voice agent.",
    persona: "Calm clinic or service-desk coordinator. Helpful, never rushed.",
    greeting: "Thank you for calling. I can help you book, reschedule, or confirm an appointment. How can I help?",
    qualifyPrompt: "Would you like to book a new slot, move an existing one, or just confirm what you already have?",
    closingPrompt: "I can lock this time, send a confirmation, or call you back if you need to check.",
    successPrompt: "Done. Your appointment is confirmed. You will get the details shortly.",
    successCriteria: "Book, reschedule, or confirm an appointment, or capture a callback time.",
    defaultSuccessDisposition: "booked",
    language: "en-IN",
    voice: "Serena",
  },
  {
    id: "leads",
    category: "lead-qualification",
    name: "Sales discovery",
    direction: "outbound",
    useCase: "Meet Ananya: the AI voice agent that turns warm leads into booked meetings.",
    persona: "Calm, warm, never pushy. Speaks slowly and clearly.",
    greeting: "Hi, this is Ananya. You asked for a callback — is now a good time for a short chat?",
    qualifyPrompt: "What were you hoping to get from this, and is this for your team this month?",
    closingPrompt: "I can book a meeting, or I can call you back at a better time.",
    successPrompt: "Lovely. I have you marked as qualified and the next meeting is noted.",
    successCriteria: "Confirm intent, company context, and a meeting or callback.",
    defaultSuccessDisposition: "qualified",
    language: "en-IN",
    voice: "Aria",
  },
  {
    id: "emi",
    category: "collections",
    name: "EMI collection",
    direction: "outbound",
    useCase: "An AI collections agent that manages EMI reminders and simplifies customer payments.",
    persona: "Respectful, clear, never threatening. Helps the customer find a way to pay.",
    greeting: "Hi, I am calling from the collections desk about your EMI. Is now a convenient time?",
    qualifyPrompt: "I can take a payment update, set a date, or note if you need another option.",
    closingPrompt: "Would you like to pay now, commit a date, or have us call back?",
    successPrompt: "Thank you. I have recorded the payment plan and we are done on this call.",
    successCriteria: "Capture a payment, a promised date, or a callback. Stop if the customer opts out.",
    defaultSuccessDisposition: "success",
    language: "hi-IN",
    voice: "Serena",
  },
  {
    id: "reminder",
    category: "reminder",
    name: "Payment reminder",
    direction: "outbound",
    useCase: "Remind customers about an upcoming due date and confirm they can pay on time.",
    persona: "Friendly reminder desk. Short, polite, easy to understand.",
    greeting: "Hi, this is a reminder about your upcoming payment. Do you have a minute?",
    qualifyPrompt: "Will you be able to complete this on the due date, or should I note another time?",
    closingPrompt: "I can mark this as confirmed, or set a reminder to call you again.",
    successPrompt: "Noted. I have confirmed the reminder. Thank you.",
    successCriteria: "Confirm the customer will pay, or schedule a follow-up.",
    defaultSuccessDisposition: "success",
    language: "en-IN",
    voice: "Serena",
  },
  {
    id: "recovery",
    category: "recovery",
    name: "Cart recovery",
    direction: "outbound",
    useCase: "Call shoppers who left items in the cart and help them complete the order.",
    persona: "Helpful store associate. Practical, not salesy.",
    greeting: "Hi, I noticed a few items were left in your cart. Would you like help completing the order?",
    qualifyPrompt: "Is there a delivery date, address, or payment question I can help with?",
    closingPrompt: "I can complete this now, send a payment link note, or call you later.",
    successPrompt: "Great. I have noted the next step for your order.",
    successCriteria: "Recover the order, capture a blocker, or schedule a callback.",
    defaultSuccessDisposition: "qualified",
    language: "en-IN",
    voice: "Aria",
  },
  {
    id: "flights",
    category: "reminder",
    name: "Flight desk",
    direction: "outbound",
    useCase: "Travel agency calling customers to confirm, change, or complete a flight booking. If they miss the call, recall them.",
    persona: "Warm travel advisor at a booking desk. Helpful, clear, never pushy.",
    greeting: "Hi, this is Ananya from Skyline Bookings. I am calling about your flight. Is now a good time?",
    qualifyPrompt: "I have your itinerary here. Should I confirm the seats, or would you rather I call back later?",
    closingPrompt: "I can lock this booking, send the ticket, or set a callback.",
    successPrompt: "Done. Your flight is confirmed and I will send the details. Safe travels.",
    successCriteria: "Confirm passenger name, route, date, or schedule a callback. Recall if no answer, busy, or dropped.",
    defaultSuccessDisposition: "booked",
    language: "en-IN",
    voice: "Serena",
  },
  {
    id: "support",
    category: "appointments",
    name: "Support concierge",
    direction: "inbound",
    useCase: "Answer customer questions and close with a resolved ticket or a specialist recall.",
    persona: "Calm, precise, empathetic.",
    greeting: "Thank you for calling. How can I help you today?",
    qualifyPrompt: "Is this about a booking, a change, or something else?",
    closingPrompt: "I can close this as resolved, or have a specialist call you back.",
    successPrompt: "All set. I have logged this for you.",
    successCriteria: "Resolve the issue or schedule a human recall.",
    defaultSuccessDisposition: "success",
    language: "en-IN",
    voice: "Aria",
  },
];
